### ISSUE TITLE
free: command not found

### ISSUE THREAD

**Issue by nitinprakash96** [easimon/maximize-build-space#15]
I was trying out this action today on `ubuntu-latest` and kept getting the following error:

```
Run easimon/maximize-build-space@master
Run echo "Memory and swap:"
Memory and swap:
/__w/_temp/c9089276-45ab-4176-ac40-c7afff117bd0.sh: line 2: free: command not found
Error: Process completed with exit code 127.
```

I wonder if we need to install packages separately? Or is it assumed that the commands required by the action comes pre-installed in the github runners?

**Comment by easimon** [comment]
On `ubuntu-latest`, `free` is usually preinstalled.. I am also testing this action once in a while against all available ubuntu runner versions, to create [this overview](https://github.com/easimon/maximize-build-space/blob/test-report/README.md).

Wild guess: you're not using it on the bare runner VM, but in a container, like this:

```yaml
jobs:
  my-job:
    runs-on: ubuntu-latest
    container:
      image: nginx:latest # or some other container
    steps:
      - name: Maximize
        uses: easimon/maximize-build-space@master
```

If that's the issue: this won't work. You cannot use this action in docker. Also just adding the missing packages to the docker image will not fix this. The LVM/remount hackery is just not doable in docker environment.
