### ISSUE TITLE
Git checkout fails after cleanup

### ISSUE THREAD

**Issue by bandrei** [easimon/maximize-build-space#21]
1. Ran the cleanup action
2. Did a git checkout, and git lfs checkout
3. Failed with exit code 1

```
Git LFS initialized.
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --filter=blob:none --depth=1 origin +refs/heads/maximize_space*:refs/remotes/origin/maximize_space* +refs/tags/maximize_space*:refs/tags/maximize_space*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 20 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --filter=blob:none --depth=1 origin +refs/heads/maximize_space*:refs/remotes/origin/maximize_space* +refs/tags/maximize_space*:refs/tags/maximize_space*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 20 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --filter=blob:none --depth=1 origin +refs/heads/maximize_space*:refs/remotes/origin/maximize_space* +refs/tags/maximize_space*:refs/tags/maximize_space*
  Error: The process '/usr/bin/git' failed with exit code 1
```

Example config:
```
name: Build sample apk
on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *' # run at 7 AM UTC
jobs:
  build:
    name: Build sample apk from develop branch
    runs-on: ubuntu-latest
    steps:
      - name: Maximize space on the runner
        uses: easimon/maximize-build-space@v7
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-haskell: 'true'
          remove-docker-images: 'true'

      # Checkout (with LFS)
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: maximize_space
          lfs: true
          sparse-checkout: |
            Assets
            Packages
            ProjectSettings
```
